// <auto-generated />
using ColegioRojasAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ColegioRojasAPI.Migrations
{
    [DbContext(typeof(ColegioContext))]
    [Migration("20240111235606_bsd")]
    partial class bsd
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ColegioRojasAPI.Models.Colegio", b =>
                {
                    b.Property<int>("ColegioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ColegioID"), 1L, 1);

                    b.Property<string>("Aforo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Aulas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ColegioID");

                    b.ToTable("Colegios");
                });
#pragma warning restore 612, 618
        }
    }
}
